# Generated by Django 5.1.4 on 2025-03-02 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
        migrations.CreateModel(
            name='LocalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_ip', models.GenericIPAddressField()),
                ('client_port', models.IntegerField()),
                ('data', models.JSONField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_datas', to='main.device')),
            ],
            options={
                'verbose_name': 'Данные из локальной сети',
                'verbose_name_plural': 'Данные из локальных сети',
            },
        ),
        migrations.CreateModel(
            name='AggregetedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('local_datas', models.ManyToManyField(related_name='aggregated_datas', to='main.localdata')),
            ],
            options={
                'verbose_name': 'Агрегированные данные',
                'verbose_name_plural': 'Агрегированные данные',
            },
        ),
    ]
