# Generated by Django 5.1.4 on 2025-03-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localdata',
            name='client_ip',
        ),
        migrations.RemoveField(
            model_name='localdata',
            name='client_port',
        ),
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localdata',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
