# Generated by Django 5.1.4 on 2025-03-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_localdata_client_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localdata',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
