# Generated by Django 5.1.4 on 2025-03-03 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_localdata_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=0)),
                ('result', models.JSONField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='main.device')),
                ('local_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='main.localdata')),
            ],
        ),
    ]
