# Generated by Django 5.1.4 on 2025-03-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_roundresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregeteddata',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Статус активности'),
        ),
        migrations.AddField(
            model_name='aggregeteddata',
            name='ready',
            field=models.BooleanField(default=False, verbose_name='Готовность данных'),
        ),
        migrations.AddField(
            model_name='aggregeteddata',
            name='waiting_device_count',
            field=models.IntegerField(default=0, verbose_name='Количество устройств в ожидании'),
        ),
    ]
