# Generated by Django 5.1.4 on 2025-03-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aggregeteddata_is_active_aggregeteddata_ready_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregeteddata',
            name='waiting_device_count',
        ),
        migrations.AddField(
            model_name='aggregeteddata',
            name='subscribed_devices',
            field=models.ManyToManyField(related_name='subscribed_devices', to='main.device'),
        ),
    ]
