# Generated by Django 5.1.4 on 2025-03-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_aggregeteddata_waiting_device_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregeteddata',
            name='epoch_count',
            field=models.IntegerField(default=0, verbose_name='Количество эпох'),
        ),
        migrations.AddField(
            model_name='aggregeteddata',
            name='round_count',
            field=models.IntegerField(default=0, verbose_name='Количество раунда'),
        ),
    ]
