# Generated by Django 5.1.4 on 2025-03-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_aggregeteddata_epoch_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
