# Generated by Django 5.1.4 on 2025-03-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_device_is_online_device_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
