# Generated by Django 5.1.4 on 2025-03-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_device_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_token',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
