# Generated by Django 5.1.4 on 2025-03-05 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_device_device_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roundresult',
            options={'verbose_name': 'Результат раунда', 'verbose_name_plural': 'Результаты раунда'},
        ),
        migrations.CreateModel(
            name='PredictResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predict_results', to='main.device')),
            ],
            options={
                'verbose_name': 'Результат предсказания',
                'verbose_name_plural': 'Результаты предсказания',
            },
        ),
    ]
