# Generated by Django 5.1.4 on 2025-11-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_customer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localdata',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='aggregeteddata',
            index=models.Index(fields=['is_active', '-created_at'], name='main_aggreg_is_acti_26131a_idx'),
        ),
    ]
