# Generated by Django 5.1.4 on 2025-11-07 06:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
import django.utils.timezone  # ← добавь этот импорт сверху


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_localdata_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundresult',
            name='avg_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roundresult',
            name='avg_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roundresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('model_name', models.CharField(db_index=True, max_length=32)),
                ('round_count', models.IntegerField(default=0)),
                ('max_rounds', models.IntegerField(default=50)),
                ('epochs', models.IntegerField(default=10)),
                ('global_weights', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('date', 'model_name'), name='uniq_train_per_date_model')],
            },
        ),
        migrations.AddField(
            model_name='roundresult',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='main.train'),
        ),
        migrations.AddIndex(
            model_name='roundresult',
            index=models.Index(fields=['round_number'], name='main_roundr_round_n_30c8a6_idx'),
        ),
        migrations.AddIndex(
            model_name='roundresult',
            index=models.Index(fields=['created_at'], name='main_roundr_created_cf817f_idx'),
        ),
        migrations.AddIndex(
            model_name='roundresult',
            index=models.Index(fields=['train', 'round_number'], name='main_roundr_train_i_16bb7c_idx'),
        ),
    ]
