# Generated by Django 5.1.4 on 2025-11-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_roundresult_avg_accuracy_roundresult_avg_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='global_confusion',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
